name: Build and Push Docker
on:
  release:
    types:
      - created
  push:
    branches:
      - main

jobs:
  push:
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: hoarder-web-oauth-timeout-fix
            target: web
          - package: hoarder-workers-oauth-timeout-fix
            target: workers
          - package: hoarder-cli-oauth-timeout-fix
            target: cli
          - package: hoarder-oauth-timeout-fix
            target: aio
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_GITHUB_PAT }}

      - name: Build ${{ matrix.package }}
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: SERVER_VERSION=nightly
          file: docker/Dockerfile
          target: ${{ matrix.target }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kaio-cesar/${{ matrix.package }}:latest,ghcr.io/kaio-cesar/${{ matrix.package }}:latest
          cache-from: type=registry,ref=ghcr.io/kaio-cesar/hoarder-build-cache:${{ matrix.target }}
          cache-to: type=registry,mode=max,ref=ghcr.io/kaio-cesar/hoarder-build-cache:${{ matrix.target }}

      - name: Build ${{ matrix.package }} (release)
        uses: docker/build-push-action@v5
        if: github.event_name == 'release'
        with:
          context: .
          build-args: SERVER_VERSION=${{ github.event.release.name }}
          file: docker/Dockerfile
          target: ${{ matrix.target }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kaio-cesar/${{ matrix.package }}:${{ github.event.release.name }},ghcr.io/kaio-cesar/${{ matrix.package }}:release,ghcr.io/kaio-cesar/${{ matrix.package }}:${{ github.event.release.name }},ghcr.io/kaio-cesar/${{ matrix.package }}:release
          cache-from: type=registry,ref=ghcr.io/kaio-cesar/hoarder-build-cache:${{ matrix.target }}
          cache-to: type=registry,mode=max,ref=ghcr.io/kaio-cesar/hoarder-build-cache:${{ matrix.target }}
